a=int(input('enter the a value :'))
b=int(input('enter the b value :'))
c=int(input('enter the c value :'))
mn=min(a,b,c)
mx=max(a,b,c)
md=(a+b+c)-(mn+mx)
print('min value :',mn)
print('max value :',md)
print('mid value :',mx)
print('ascending order :',mn,md,mx,sep=',')
print('descending order :',mx,md,mn,sep=',')